using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class camera : MonoBehaviour
{
    public Transform target;

    public float smoothSpeed = 3;
    public Vector2 offset;
    public float limitMinX, limitMaxX, limitMinY, limitMaxY;
    public Transform focusPoint;
    Transform endingPoint;
    GameObject Dragon;
    GameObject Hades;
    GameObject Target;
    public float focusDuration = 5f;
    float cameraHalfWidth, cameraHalfHeight;
    public bool isFocusing = false;

    private void Start()
    {
        if (SceneManager.GetActiveScene().name == "second_stage")
        {
            Dragon = GameObject.Find("Dragon");
            focusPoint = Dragon.transform;
            Dragon.SetActive(false);
        }
        if (SceneManager.GetActiveScene().name == "third_stage")
        {
            Hades = GameObject.Find("Hades");
            Target = GameObject.Find("Target");
            focusPoint = Hades.transform;
            endingPoint=Target.transform;
            Hades.SetActive(false);
        }
        Application.targetFrameRate = 60;
        cameraHalfWidth = Camera.main.aspect * Camera.main.orthographicSize;
        cameraHalfHeight = Camera.main.orthographicSize;
    }

    private void LateUpdate()
    {
        if (!isFocusing)
        {
            FollowTarget();
        }
    }
    void FollowTarget()
    {
        Vector3 desiredPosition = new Vector3(
            Mathf.Clamp(target.position.x + offset.x, limitMinX + cameraHalfWidth, limitMaxX - cameraHalfWidth),   // X
            Mathf.Clamp(target.position.y + offset.y, limitMinY + cameraHalfHeight, limitMaxY - cameraHalfHeight), // Y
            -10);                                                                                                  // Z
        transform.position = Vector3.Lerp(transform.position, desiredPosition, Time.deltaTime * smoothSpeed);
    }
    public void TriggerFocus()
    {
        if (!isFocusing)
        {
            StartCoroutine(FocusOnPoint());
        }
    }
    public void End()
    {
        if (!isFocusing)
        {
            StartCoroutine(EndingScene());
        }
    }

    private IEnumerator FocusOnPoint()
    {
        isFocusing = true;
        // focusPoint РЇФЁЗЮ РЬЕП
        Vector3 focusPosition = new Vector3(
            Mathf.Clamp(focusPoint.position.x, limitMinX + cameraHalfWidth, limitMaxX - cameraHalfWidth),   // X
            Mathf.Clamp(focusPoint.position.y, limitMinY + cameraHalfHeight, limitMaxY - cameraHalfHeight), // Y
            -10);                                                                                           // Z

        float elapsedTime = 0f;
        Vector3 initialPosition = transform.position;

        // СіСЄЕШ НУАЃ ЕПОШ focusPointИІ ЧтЧи ФЋИоЖѓ РЬЕП
        while (elapsedTime < focusDuration)
        {
            transform.position = Vector3.Lerp(initialPosition, focusPosition, elapsedTime / focusDuration);
            elapsedTime += Time.deltaTime;
            yield return null;
        }
        if (SceneManager.GetActiveScene().name == "second_stage") Dragon.SetActive(true);
        else if (SceneManager.GetActiveScene().name == "third_stage" && !Hades.GetComponent<Hades>().isDead)
        {
            Hades.GetComponent<HadesAI>().enabled = false;
            Hades.SetActive(true);
        }
        else
        {
            Hades.GetComponent<Hades>().Respawn();
        }
        if(SceneManager.GetActiveScene().name == "second_stage" || SceneManager.GetActiveScene().name == "third_stage" && !Hades.GetComponent<Hades>().revived)
            SFXManager.Instance.PlaySound(SFXManager.Instance.spawn);
        yield return new WaitForSeconds(2.0f);
        // focusDurationРЬ СіГ­ ШФ ФГИЏХЭИІ ДйНУ ЕћЖѓАЈ
        isFocusing = false;
        if(SceneManager.GetActiveScene().name == "third_stage")
            Hades.GetComponent<HadesAI>().enabled = true;
        
    }
    private IEnumerator EndingScene()
    {
        SFXManager.Instance.StopAllCoroutines();
        GameObject.Find("trigger").SetActive(false);

        // АшДм ПРКъСЇЦЎЕщРЛ АЂАЂ РЬЕПНУХААэ, y СТЧЅИІ УМХЉЧЯДТ ФкЗчЦОРЛ НУРлЧеДЯДй.
        StartCoroutine(MoveAndStopAtTarget(GameObject.Find("Stair1")));
        StartCoroutine(MoveAndStopAtTarget(GameObject.Find("Stair2")));
        StartCoroutine(MoveAndStopAtTarget(GameObject.Find("Stair3")));
        BGMManager_Hades.Instance.PlaySound(BGMManager_Hades.Instance.rs);
        isFocusing = true;

        // focusPoint РЇФЁЗЮ РЬЕП
        Vector3 focusPosition = new Vector3(
            Mathf.Clamp(endingPoint.position.x, limitMinX + cameraHalfWidth, limitMaxX - cameraHalfWidth),   // X
            Mathf.Clamp(endingPoint.position.y, limitMinY + cameraHalfHeight, limitMaxY - cameraHalfHeight), // Y
            -10);                                                                                           // Z

        float elapsedTime = 0f;
        Vector3 initialPosition = transform.position;

        // СіСЄЕШ НУАЃ ЕПОШ focusPointИІ ЧтЧи ФЋИоЖѓ РЬЕП
        while (elapsedTime < focusDuration)
        {
            transform.position = Vector3.Lerp(initialPosition, focusPosition, elapsedTime / focusDuration);
            elapsedTime += Time.deltaTime;
            yield return null;
        }

        yield return new WaitForSeconds(7.0f);

        // focusDurationРЬ СіГ­ ШФ ФГИЏХЭИІ ДйНУ ЕћЖѓАЈ
        isFocusing = false;
        GameObject.Find("sword_man").GetComponent<Sword_Man>().InputLock();
        GameObject.Find("sword_man").GetComponent<Sword_Man>().MoveRight();
        GameObject.Find("sword_man").GetComponent<Rigidbody2D>().velocity = Vector3.right * 0.2f;
        yield return new WaitForSeconds(2.5f);
        SceneManager.LoadScene("Ending");
    }

    // АшДм ПРКъСЇЦЎИІ РЬЕПНУХААэ, y СТЧЅАЁ 0 РЬЛѓРЬ ЕЧИщ МгЕЕИІ 0РИЗЮ МГСЄЧЯДТ ФкЗчЦО
    private IEnumerator MoveAndStopAtTarget(GameObject stair)
    {
        Rigidbody2D rb = stair.GetComponent<Rigidbody2D>();
        rb.velocity = Vector3.up * 0.8f;

        // y СТЧЅАЁ 0 РЬЛѓРЬ ЕЩ ЖЇБюСі ЙнКЙ ШЎРЮ
        while (stair.transform.position.y < 0.0f)
        {
            yield return null;
        }

        // ИёЧЅПЁ ЕЕДоЧЯИщ МгЕЕИІ 0РИЗЮ МГСЄ
        rb.velocity = Vector3.zero;
        Debug.Log(stair.name + " ЕЕТј");
    }
}
